ALTER TABLE `facultyMaster`
  ADD COLUMN IF NOT EXISTS `stateId` INTEGER NULL AFTER `district`,
  ADD COLUMN IF NOT EXISTS `cityId` INTEGER NULL AFTER `state`,
  ADD COLUMN IF NOT EXISTS `city` VARCHAR(100) NULL AFTER `cityId`,
  ADD COLUMN IF NOT EXISTS `zipcodeId` INTEGER NULL AFTER `city`;
