-- Additive only: create studentRollNumber table (no data loss)
CREATE TABLE IF NOT EXISTS `studentRollNumber` (
  `rollId` INT NOT NULL AUTO_INCREMENT,
  `rollNo` VARCHAR(12) NOT NULL,
  `studentId` INT NOT NULL,
  `enrollmentId` INT NULL,
  `sessionId` INT NULL,
  `programId` INT NULL,
  `admissionYear` VARCHAR(4) NOT NULL,
  `collegeCode` VARCHAR(3) NOT NULL,
  `programCode` VARCHAR(2) NOT NULL,
  `serialNo` VARCHAR(3) NOT NULL,
  `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CreatedBy` VARCHAR(255) NOT NULL,
  `UpdatedOn` DATETIME(3) NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  `IsActive` BOOLEAN NOT NULL DEFAULT true,
  `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
  `DeletedRemarks` VARCHAR(255) NULL,
  `DeletedOn` DATETIME(3) NULL,
  `DeletedBy` VARCHAR(255) NULL,
  `Remarks` VARCHAR(255) NULL,
  PRIMARY KEY (`rollId`),
  UNIQUE KEY `studentRollNumber_rollNo_key` (`rollNo`),
  UNIQUE KEY `studentRollNumber_studentId_admissionYear_key` (`studentId`, `admissionYear`),
  KEY `studentRollNumber_studentId_idx` (`studentId`),
  KEY `studentRollNumber_enrollmentId_idx` (`enrollmentId`),
  KEY `studentRollNumber_sessionId_idx` (`sessionId`),
  KEY `studentRollNumber_programId_idx` (`programId`),
  KEY `studentRollNumber_admissionYear_idx` (`admissionYear`),
  CONSTRAINT `studentRollNumber_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `students` (`StudentRegistrationId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `studentRollNumber_enrollmentId_fkey` FOREIGN KEY (`enrollmentId`) REFERENCES `studentEnrollment` (`enrollmentId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `studentRollNumber_sessionId_fkey` FOREIGN KEY (`sessionId`) REFERENCES `admissionSessions` (`admissionSessionId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `studentRollNumber_programId_fkey` FOREIGN KEY (`programId`) REFERENCES `programs` (`programId`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
