-- Safe DDL for creating Exam Attendance tables without data loss
CREATE TABLE IF NOT EXISTS `examAttendance` (
  `attendanceId` INT NOT NULL AUTO_INCREMENT,
  `academicSessionId` INT NULL,
  `examinationDetailId` INT NULL,
  `programId` INT NULL,
  `paperId` INT NULL,
  `subjectName` VARCHAR(255) NULL,
  `paperType` VARCHAR(100) NULL,
  `paperCode` VARCHAR(100) NULL,
  `paperName` VARCHAR(255) NULL,
  `examDate` DATETIME(3) NOT NULL,
  `examTime` VARCHAR(100) NULL,
  `shift` VARCHAR(50) NULL,
  `isLocked` BOOLEAN NOT NULL DEFAULT false,
  `lockedAt` DATETIME(3) NULL,
  `lockedBy` VARCHAR(255) NULL,
  `totalStudents` INT NOT NULL DEFAULT 0,
  `totalPresent` INT NOT NULL DEFAULT 0,
  `totalAbsent` INT NOT NULL DEFAULT 0,
  `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CreatedBy` VARCHAR(255) NULL,
  `UpdatedOn` DATETIME(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `UpdatedBy` VARCHAR(255) NULL,
  `IsActive` BOOLEAN NOT NULL DEFAULT true,
  `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (`attendanceId`),
  INDEX `examAttendance_academicSessionId_idx` (`academicSessionId`),
  INDEX `examAttendance_examinationDetailId_idx` (`examinationDetailId`),
  INDEX `examAttendance_programId_idx` (`programId`),
  INDEX `examAttendance_paperId_idx` (`paperId`),
  UNIQUE INDEX `examAttendance_unique_idx` (`academicSessionId`, `examinationDetailId`, `programId`, `paperId`, `examDate`, `shift`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `examAttendanceDetail` (
  `attendanceDetailId` INT NOT NULL AUTO_INCREMENT,
  `attendanceId` INT NOT NULL,
  `studentId` INT NOT NULL,
  `rollNo` VARCHAR(100) NOT NULL,
  `studentName` VARCHAR(255) NOT NULL,
  `fatherName` VARCHAR(255) NULL,
  `examCategory` VARCHAR(100) NULL,
  `mobileNo` VARCHAR(50) NULL,
  `attendanceStatus` VARCHAR(10) NOT NULL DEFAULT 'P',
  `answerBookletNo` VARCHAR(100) NULL,
  `remarks` VARCHAR(255) NULL,
  `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CreatedBy` VARCHAR(255) NULL,
  `UpdatedOn` DATETIME(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `UpdatedBy` VARCHAR(255) NULL,
  PRIMARY KEY (`attendanceDetailId`),
  INDEX `examAttendanceDetail_attendanceId_idx` (`attendanceId`),
  INDEX `examAttendanceDetail_studentId_idx` (`studentId`),
  CONSTRAINT `fk_examAttendanceDetail_attendance` FOREIGN KEY (`attendanceId`) REFERENCES `examAttendance` (`attendanceId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_examAttendanceDetail_student` FOREIGN KEY (`studentId`) REFERENCES `students` (`StudentRegistrationId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
