-- Additive only: create StudentExam tables. Does not drop examLoginMaster columns.

CREATE TABLE IF NOT EXISTS `studentExam` (
    `studentExamId` INTEGER NOT NULL AUTO_INCREMENT,
    `studentId` INTEGER NOT NULL,
    `registrationNo` VARCHAR(100) NULL,
    `enrollmentNo` VARCHAR(100) NULL,
    `studentNameEng` VARCHAR(255) NULL,
    `studentNameHindi` VARCHAR(255) NULL,
    `fatherName` VARCHAR(255) NULL,
    `motherName` VARCHAR(255) NULL,
    `dob` DATETIME(3) NULL,
    `mobileNo` VARCHAR(20) NULL,
    `emailId` VARCHAR(255) NULL,
    `rollNo` VARCHAR(100) NULL,
    `admissionNo` VARCHAR(100) NULL,
    `barNo` VARCHAR(100) NULL,
    `examFormNo` VARCHAR(100) NULL,
    `uniqueNo` VARCHAR(100) NULL,
    `examTypeId` INTEGER NULL,
    `examType` VARCHAR(50) NULL,
    `courseCategoryId` INTEGER NULL,
    `courseCategory` VARCHAR(255) NULL,
    `courseId` INTEGER NULL,
    `courseShortName` VARCHAR(255) NULL,
    `yearId` INTEGER NULL,
    `yearName` VARCHAR(100) NULL,
    `semId` INTEGER NULL,
    `semName` VARCHAR(100) NULL,
    `sessionId` INTEGER NULL,
    `studentImgURL` VARCHAR(2000) NULL,
    `studentImgName` VARCHAR(255) NULL,
    `studentSignImgURL` VARCHAR(2000) NULL,
    `studentSignImgName` VARCHAR(255) NULL,
    `examFeeId` INTEGER NULL,
    `totalExamFee` DOUBLE NULL DEFAULT 0.0,
    `isFeePaymentDone` BOOLEAN NOT NULL DEFAULT false,
    `totalPaidAmount` DOUBLE NULL DEFAULT 0.0,
    `bankTxnNo` VARCHAR(100) NULL,
    `bankTxnDetail` TEXT NULL,
    `feePaymentDate` DATETIME(3) NULL,
    `isExamFeePaid` BOOLEAN NOT NULL DEFAULT false,
    `isExamFormFinalSubmit` BOOLEAN NOT NULL DEFAULT false,
    `isExamFormPrintTaken` BOOLEAN NOT NULL DEFAULT false,
    `isExamFormSendOnEmail` BOOLEAN NOT NULL DEFAULT false,
    `isExamFormVerify` BOOLEAN NOT NULL DEFAULT false,
    `verifyBy` VARCHAR(255) NULL,
    `verifyDate` DATETIME(3) NULL,
    `verificationRemarks` TEXT NULL,
    `isReadyForAdmitCard` BOOLEAN NOT NULL DEFAULT false,
    `selectedPaperIds` VARCHAR(500) NULL,
    `examPaymentIds` VARCHAR(500) NULL,
    `examinationDetailId` INTEGER NULL,
    `examinationName` VARCHAR(100) NULL,
    `Remarks` VARCHAR(255) NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
    `DeletedRemarks` VARCHAR(255) NULL,
    `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedBy` VARCHAR(255) NULL,
    `UpdatedOn` DATETIME(3) NULL,
    `UpdatedBy` VARCHAR(255) NULL,
    INDEX `studentExam_studentId_idx`(`studentId`),
    INDEX `studentExam_enrollmentNo_idx`(`enrollmentNo`),
    INDEX `studentExam_registrationNo_idx`(`registrationNo`),
    INDEX `studentExam_courseId_idx`(`courseId`),
    INDEX `studentExam_examFeeId_idx`(`examFeeId`),
    INDEX `studentExam_examTypeId_idx`(`examTypeId`),
    INDEX `studentExam_yearId_idx`(`yearId`),
    INDEX `studentExam_semId_idx`(`semId`),
    INDEX `studentExam_sessionId_idx`(`sessionId`),
    INDEX `studentExam_examinationDetailId_idx`(`examinationDetailId`),
    PRIMARY KEY (`studentExamId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `studentExamPaper` (
    `studentExamPaperId` INTEGER NOT NULL AUTO_INCREMENT,
    `studentExamId` INTEGER NOT NULL,
    `studentId` INTEGER NOT NULL,
    `enrollmentId` INTEGER NULL,
    `enrollmentNo` VARCHAR(100) NULL,
    `paperId` INTEGER NULL,
    `paperType` VARCHAR(100) NULL,
    `subjectName` VARCHAR(255) NULL,
    `paperName` VARCHAR(255) NULL,
    `paperCode` VARCHAR(100) NULL,
    `paperNameWithCode` VARCHAR(255) NULL,
    `isChosen` BOOLEAN NOT NULL DEFAULT true,
    `Remarks` VARCHAR(255) NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
    `DeletedRemarks` VARCHAR(255) NULL,
    `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedBy` VARCHAR(255) NULL,
    `UpdatedOn` DATETIME(3) NULL,
    `UpdatedBy` VARCHAR(255) NULL,
    INDEX `studentExamPaper_studentExamId_idx`(`studentExamId`),
    INDEX `studentExamPaper_studentId_idx`(`studentId`),
    INDEX `studentExamPaper_enrollmentId_idx`(`enrollmentId`),
    INDEX `studentExamPaper_paperId_idx`(`paperId`),
    PRIMARY KEY (`studentExamPaperId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
