CREATE TABLE IF NOT EXISTS `facultyEducation` (
    `facultyEducationId` INTEGER NOT NULL AUTO_INCREMENT,
    `facultyId` INTEGER NOT NULL,
    `facultyQualificationId` INTEGER NULL,
    `qualification` VARCHAR(255) NULL,
    `facultySpecializationId` INTEGER NULL,
    `specializationSubject` VARCHAR(255) NULL,
    `university` VARCHAR(255) NULL,
    `collegeInstitute` VARCHAR(255) NULL,
    `passingYear` INTEGER NULL,
    `certificateUrl` VARCHAR(2000) NULL,
    `certificateName` VARCHAR(255) NULL,
    `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedBy` VARCHAR(255) NOT NULL,
    `UpdatedOn` DATETIME(3) NULL,
    `UpdatedBy` VARCHAR(255) NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
    `DeletedRemarks` VARCHAR(255) NULL,
    `DeletedOn` DATETIME(3) NULL,
    `DeletedBy` VARCHAR(255) NULL,
    `Remarks` VARCHAR(255) NULL,
    INDEX `facultyEducation_facultyId_idx`(`facultyId`),
    PRIMARY KEY (`facultyEducationId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
