-- Student Promotion tables (From → To)
-- Run manually if not using prisma migrate

CREATE TABLE IF NOT EXISTS `promotion` (
  `promotionId` INT NOT NULL AUTO_INCREMENT,
  `sessionIdFrom` INT NOT NULL,
  `yearIdFrom` INT NOT NULL,
  `semIdFrom` INT NULL,
  `courseCategoryIdFrom` INT NOT NULL,
  `courseIdFrom` INT NOT NULL,
  `subjectIdFrom` INT NULL,
  `sessionIdTo` INT NOT NULL,
  `yearIdTo` INT NOT NULL,
  `semIdTo` INT NULL,
  `courseCategoryIdTo` INT NOT NULL,
  `courseIdTo` INT NOT NULL,
  `subjectIdTo` INT NULL,
  `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CreatedBy` VARCHAR(255) NULL,
  `UpdatedOn` DATETIME(3) NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  `IsActive` BOOLEAN NOT NULL DEFAULT true,
  `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
  `DeletedRemarks` VARCHAR(255) NULL,
  `DeletedOn` DATETIME(3) NULL,
  `DeletedBy` VARCHAR(255) NULL,
  `Remarks` VARCHAR(255) NULL,
  PRIMARY KEY (`promotionId`),
  INDEX `promotion_from_idx` (`sessionIdFrom`, `yearIdFrom`, `semIdFrom`, `courseIdFrom`),
  INDEX `promotion_to_idx` (`sessionIdTo`, `yearIdTo`, `semIdTo`, `courseIdTo`),
  CONSTRAINT `promotion_sessionFrom_fkey` FOREIGN KEY (`sessionIdFrom`) REFERENCES `academicSessionMaster`(`academicSessionId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_yearFrom_fkey` FOREIGN KEY (`yearIdFrom`) REFERENCES `yearMaster`(`yearId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_semFrom_fkey` FOREIGN KEY (`semIdFrom`) REFERENCES `semesterMaster`(`semId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `promotion_courseCategoryFrom_fkey` FOREIGN KEY (`courseCategoryIdFrom`) REFERENCES `programCategory`(`programCategoryId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_courseFrom_fkey` FOREIGN KEY (`courseIdFrom`) REFERENCES `programs`(`programId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_subjectFrom_fkey` FOREIGN KEY (`subjectIdFrom`) REFERENCES `subjectMaster`(`subjectId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `promotion_sessionTo_fkey` FOREIGN KEY (`sessionIdTo`) REFERENCES `academicSessionMaster`(`academicSessionId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_yearTo_fkey` FOREIGN KEY (`yearIdTo`) REFERENCES `yearMaster`(`yearId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_semTo_fkey` FOREIGN KEY (`semIdTo`) REFERENCES `semesterMaster`(`semId`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `promotion_courseCategoryTo_fkey` FOREIGN KEY (`courseCategoryIdTo`) REFERENCES `programCategory`(`programCategoryId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_courseTo_fkey` FOREIGN KEY (`courseIdTo`) REFERENCES `programs`(`programId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotion_subjectTo_fkey` FOREIGN KEY (`subjectIdTo`) REFERENCES `subjectMaster`(`subjectId`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `promotionDetail` (
  `promotionDetailId` INT NOT NULL AUTO_INCREMENT,
  `promotionId` INT NOT NULL,
  `studentId` INT NOT NULL,
  `regNo` VARCHAR(100) NULL,
  `enrollmentNo` VARCHAR(100) NULL,
  `rollNo` VARCHAR(100) NULL,
  `examMode` VARCHAR(100) NULL,
  `examResult` VARCHAR(100) NULL,
  `isPromoted` BOOLEAN NOT NULL DEFAULT true,
  `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CreatedBy` VARCHAR(255) NULL,
  `UpdatedOn` DATETIME(3) NULL,
  `UpdatedBy` VARCHAR(255) NULL,
  `IsActive` BOOLEAN NOT NULL DEFAULT true,
  `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
  `DeletedRemarks` VARCHAR(255) NULL,
  `DeletedOn` DATETIME(3) NULL,
  `DeletedBy` VARCHAR(255) NULL,
  `Remarks` VARCHAR(255) NULL,
  PRIMARY KEY (`promotionDetailId`),
  INDEX `promotionDetail_promotionId_idx` (`promotionId`),
  INDEX `promotionDetail_studentId_idx` (`studentId`),
  INDEX `promotionDetail_rollNo_idx` (`rollNo`),
  CONSTRAINT `promotionDetail_promotion_fkey` FOREIGN KEY (`promotionId`) REFERENCES `promotion`(`promotionId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `promotionDetail_student_fkey` FOREIGN KEY (`studentId`) REFERENCES `students`(`StudentRegistrationId`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
