CREATE TABLE IF NOT EXISTS `facultyMaster` (
    `facultyId` INTEGER NOT NULL AUTO_INCREMENT,
    `employeeId` CHAR(6) NOT NULL,
    `employeTypeId` INTEGER NOT NULL,
    `employeTypeName` VARCHAR(100) NOT NULL,
    `employeeCategoryId` INTEGER NOT NULL,
    `employeeCategoryName` VARCHAR(100) NOT NULL,
    `employeeDesignationId` INTEGER NOT NULL,
    `employeeDesignationName` VARCHAR(100) NOT NULL,
    `employeeDepartmentId` INTEGER NOT NULL,
    `employeeDepartmentName` VARCHAR(100) NOT NULL,
    `employeeName` VARCHAR(255) NOT NULL,
    `fatherOrHusbandName` VARCHAR(255) NULL,
    `gender` VARCHAR(50) NULL,
    `dateOfBirth` DATETIME(3) NULL,
    `aadharNo` VARCHAR(50) NULL,
    `panNo` VARCHAR(20) NULL,
    `maritalStatus` VARCHAR(50) NULL,
    `religion` VARCHAR(100) NULL,
    `category` VARCHAR(100) NULL,
    `bloodGroup` VARCHAR(20) NULL,
    `mobileNo` VARCHAR(20) NULL,
    `alternateMobileNo` VARCHAR(20) NULL,
    `personalEmail` VARCHAR(255) NULL,
    `officialEmail` VARCHAR(255) NULL,
    `address` TEXT NULL,
    `district` VARCHAR(100) NULL,
    `stateId` INTEGER NULL,
    `state` VARCHAR(100) NULL,
    `cityId` INTEGER NULL,
    `city` VARCHAR(100) NULL,
    `zipcodeId` INTEGER NULL,
    `pincode` VARCHAR(20) NULL,
    `dateOfJoining` DATETIME(3) NULL,
    `dateOfConfirmation` DATETIME(3) NULL,
    `bankName` VARCHAR(255) NULL,
    `ifscCode` VARCHAR(20) NULL,
    `accountNumber` VARCHAR(30) NULL,
    `branch` VARCHAR(255) NULL,
    `payScale` VARCHAR(100) NULL,
    `basicSalary` DECIMAL(12, 2) NULL,
    `pfApplicable` BOOLEAN NOT NULL DEFAULT false,
    `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedBy` VARCHAR(255) NOT NULL,
    `UpdatedOn` DATETIME(3) NULL,
    `UpdatedBy` VARCHAR(255) NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
    `DeletedRemarks` VARCHAR(255) NULL,
    `DeletedOn` DATETIME(3) NULL,
    `DeletedBy` VARCHAR(255) NULL,
    `Remarks` VARCHAR(255) NULL,
    UNIQUE INDEX `facultyMaster_employeeId_key`(`employeeId`),
    UNIQUE INDEX `facultyMaster_aadharNo_key`(`aadharNo`),
    UNIQUE INDEX `facultyMaster_panNo_key`(`panNo`),
    INDEX `facultyMaster_employeTypeId_idx`(`employeTypeId`),
    INDEX `facultyMaster_employeeCategoryId_idx`(`employeeCategoryId`),
    INDEX `facultyMaster_employeeDesignationId_idx`(`employeeDesignationId`),
    INDEX `facultyMaster_employeeDepartmentId_idx`(`employeeDepartmentId`),
    INDEX `facultyMaster_stateId_idx`(`stateId`),
    INDEX `facultyMaster_cityId_idx`(`cityId`),
    INDEX `facultyMaster_zipcodeId_idx`(`zipcodeId`),
    PRIMARY KEY (`facultyId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
