-- Safe DDL for creating Exam Marks tables without data loss
CREATE TABLE IF NOT EXISTS `examMarks` (
  `marksId` INT NOT NULL AUTO_INCREMENT,
  `academicSessionId` INT NULL,
  `examinationDetailId` INT NULL,
  `programId` INT NULL,
  `yearId` INT NULL,
  `semId` INT NULL,
  `paperId` INT NULL,
  `subjectName` VARCHAR(255) NULL,
  `paperType` VARCHAR(100) NULL,
  `paperCode` VARCHAR(100) NULL,
  `paperName` VARCHAR(255) NULL,
  `marksType` VARCHAR(50) NOT NULL,
  `maxMarks` FLOAT NULL,
  `minMarks` FLOAT NULL,
  `isLocked` BOOLEAN NOT NULL DEFAULT false,
  `lockedAt` DATETIME(3) NULL,
  `lockedBy` VARCHAR(255) NULL,
  `totalStudents` INT NOT NULL DEFAULT 0,
  `totalEntered` INT NOT NULL DEFAULT 0,
  `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CreatedBy` VARCHAR(255) NULL,
  `UpdatedOn` DATETIME(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `UpdatedBy` VARCHAR(255) NULL,
  `IsActive` BOOLEAN NOT NULL DEFAULT true,
  `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (`marksId`),
  INDEX `examMarks_academicSessionId_idx` (`academicSessionId`),
  INDEX `examMarks_examinationDetailId_idx` (`examinationDetailId`),
  INDEX `examMarks_programId_idx` (`programId`),
  INDEX `examMarks_paperId_idx` (`paperId`),
  UNIQUE INDEX `examMarks_unique_idx` (`academicSessionId`, `examinationDetailId`, `programId`, `yearId`, `semId`, `paperId`, `marksType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `examMarksDetail` (
  `marksDetailId` INT NOT NULL AUTO_INCREMENT,
  `marksId` INT NOT NULL,
  `studentId` INT NOT NULL,
  `rollNo` VARCHAR(100) NOT NULL,
  `studentName` VARCHAR(255) NOT NULL,
  `fatherName` VARCHAR(255) NULL,
  `examType` VARCHAR(100) NULL DEFAULT 'Regular',
  `marksObtained` FLOAT NULL,
  `marksInWords` VARCHAR(255) NULL,
  `isAbsent` BOOLEAN NOT NULL DEFAULT false,
  `remarks` VARCHAR(255) NULL,
  `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `CreatedBy` VARCHAR(255) NULL,
  `UpdatedOn` DATETIME(3) NULL ON UPDATE CURRENT_TIMESTAMP(3),
  `UpdatedBy` VARCHAR(255) NULL,
  PRIMARY KEY (`marksDetailId`),
  INDEX `examMarksDetail_marksId_idx` (`marksId`),
  INDEX `examMarksDetail_studentId_idx` (`studentId`),
  CONSTRAINT `fk_examMarksDetail_marks` FOREIGN KEY (`marksId`) REFERENCES `examMarks` (`marksId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_examMarksDetail_student` FOREIGN KEY (`studentId`) REFERENCES `students` (`StudentRegistrationId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
