CREATE TABLE IF NOT EXISTS `pramanDetailsMaster` (
    `pramanDetailsId` INTEGER NOT NULL AUTO_INCREMENT,
    `pramanId` INTEGER NULL,
    `pramanName` VARCHAR(255) NULL,
    `subParameterId` INTEGER NULL,
    `subParameterName` VARCHAR(255) NULL,
    `monthId` INTEGER NULL,
    `monthName` VARCHAR(100) NULL,
    `academicYearId` INTEGER NULL,
    `academicYearName` VARCHAR(100) NULL,
    `attachment` VARCHAR(2000) NULL,
    `pramanResId` INTEGER NULL,
    `responseName` VARCHAR(255) NULL,
    `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedBy` VARCHAR(255) NOT NULL,
    `UpdatedOn` DATETIME(3) NULL,
    `UpdatedBy` VARCHAR(255) NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
    `DeletedRemarks` VARCHAR(255) NULL,
    `DeletedOn` DATETIME(3) NULL,
    `DeletedBy` VARCHAR(255) NULL,
    `Remarks` VARCHAR(255) NULL,
    PRIMARY KEY (`pramanDetailsId`),
    INDEX `pramanDetailsMaster_pramanId_idx`(`pramanId`),
    INDEX `pramanDetailsMaster_subParameterId_idx`(`subParameterId`),
    INDEX `pramanDetailsMaster_academicYearId_idx`(`academicYearId`),
    INDEX `pramanDetailsMaster_pramanResId_idx`(`pramanResId`),
    CONSTRAINT `pramanDetailsMaster_pramanId_fkey` FOREIGN KEY (`pramanId`) REFERENCES `pramanMaster` (`pramanId`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `pramanDetailsMaster_subParameterId_fkey` FOREIGN KEY (`subParameterId`) REFERENCES `pramanSubParameterMaster` (`subPramanParameterId`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `pramanDetailsMaster_academicYearId_fkey` FOREIGN KEY (`academicYearId`) REFERENCES `academicYearMaster` (`academicYearId`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `pramanDetailsMaster_pramanResId_fkey` FOREIGN KEY (`pramanResId`) REFERENCES `pramanResponseMaster` (`pramanResponseId`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
