CREATE TABLE IF NOT EXISTS `facultyResearch` (
    `facultyResearchId` INTEGER NOT NULL AUTO_INCREMENT,
    `facultyId` INTEGER NOT NULL,
    `scholarId` VARCHAR(100) NULL,
    `vidwanId` VARCHAR(100) NULL,
    `orcid` VARCHAR(50) NULL,
    `scopusId` VARCHAR(100) NULL,
    `researcherId` VARCHAR(100) NULL,
    `researchArea` VARCHAR(255) NULL,
    `researchGateId` VARCHAR(100) NULL,
    `researchAcademicProfile` TEXT NULL,
    `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedBy` VARCHAR(255) NOT NULL,
    `UpdatedOn` DATETIME(3) NULL,
    `UpdatedBy` VARCHAR(255) NULL,
    `IsActive` BOOLEAN NOT NULL DEFAULT true,
    `IsDeleted` BOOLEAN NOT NULL DEFAULT false,
    `DeletedRemarks` VARCHAR(255) NULL,
    `DeletedOn` DATETIME(3) NULL,
    `DeletedBy` VARCHAR(255) NULL,
    `Remarks` VARCHAR(255) NULL,
    UNIQUE INDEX `facultyResearch_facultyId_key`(`facultyId`),
    PRIMARY KEY (`facultyResearchId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
