CREATE TABLE IF NOT EXISTS `attendanceDays` (
    `attendanceDaysId` INT NOT NULL AUTO_INCREMENT,
    `studentId` INT NULL,
    `studentEnrollmentId` INT NULL,
    `studentName` VARCHAR(255) NULL,
    `enrollmentNumber` VARCHAR(100) NULL,
    `fathersName` VARCHAR(255) NULL,
    `academicSessionId` INT NULL,
    `academicSessionName` VARCHAR(100) NULL,
    `sessionId` INT NULL,
    `sessionName` VARCHAR(100) NULL,
    `programCategoryId` INT NULL,
    `programCategoryName` VARCHAR(100) NULL,
    `programId` INT NULL,
    `programName` VARCHAR(100) NULL,
    `yearId` INT NULL,
    `yearName` VARCHAR(100) NULL,
    `semId` INT NULL,
    `semName` VARCHAR(100) NULL,
    `monthId` INT NULL,
    `monthName` VARCHAR(100) NULL,
    `academicYearId` INT NULL,
    `academicYearname` VARCHAR(100) NULL,
    `teachingDays` INT NULL,
    `presentDays` INT NULL,
    `totalAttendancePercentage` DOUBLE NULL,
    `CreatedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedBy` VARCHAR(255) NOT NULL,
    `UpdatedOn` DATETIME(3) NULL,
    `UpdatedBy` VARCHAR(255) NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `DeletedRemarks` VARCHAR(255) NULL,
    `DeletedOn` DATETIME(3) NULL,
    `DeletedBy` VARCHAR(255) NULL,
    `Remarks` VARCHAR(255) NULL,

    INDEX `attendanceDays_studentId_idx`(`studentId`),
    INDEX `attendanceDays_studentEnrollmentId_idx`(`studentEnrollmentId`),
    INDEX `attendanceDays_academicSessionId_idx`(`academicSessionId`),
    INDEX `attendanceDays_programCategoryId_idx`(`programCategoryId`),
    INDEX `attendanceDays_programId_idx`(`programId`),
    INDEX `attendanceDays_yearId_idx`(`yearId`),
    INDEX `attendanceDays_semId_idx`(`semId`),
    INDEX `attendanceDays_monthId_idx`(`monthId`),
    INDEX `attendanceDays_academicYearId_idx`(`academicYearId`),
    PRIMARY KEY (`attendanceDaysId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
