export enum TenantType {
  UNIVERSITY = 'UNIVERSITY',
  COLLEGE = 'COLLEGE',
  B_ED = 'B_ED',
  D_EL_ED = 'D_EL_ED',
  ENGINEERING = 'ENGINEERING',
  MEDICAL = 'MEDICAL',
  PHARMACY = 'PHARMACY',
  NURSING = 'NURSING',
  LAW = 'LAW',
  POLYTECHNIC = 'POLYTECHNIC',
  ITI = 'ITI',
  AUTONOMOUS = 'AUTONOMOUS',
  INSTITUTE = 'INSTITUTE',
  SCHOOL = 'SCHOOL',
}

export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TRIAL = 'TRIAL',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  ARCHIVED = 'ARCHIVED',
}
